version: '3'
services:
  redis:
    build: ./redis
    ports:
      - "36379:6379"
    networks:
      - net-web
    volumes:
      - ./redis/data:/data                                     # data dir
      - ./redis/conf/redis.conf:/usr/local/redis/redis.conf    # Configuration file
      - ./redis/logs/redis.log:/usr/local/logs/redis.log       # logs file
    restart: always
    container_name: redis

  mysql:
    depends_on:
      - redis
    build: ./mysql
    ports:
      - "33306:3306"
    networks:
      - net-web
    volumes:
      - ./mysql/data:/var/lib/mysql        # data dir
      - ./mysql/logs:/var/log/mysql        # errlog and slowquery
      #- ./mysql/conf:/etc/mysql            # Configuration file
    environment:
      - MYSQL_ROOT_PWD=123456
    restart: always
    container_name: mysql

  mongodb:
    depends_on:
      - redis
    build: ./mongodb
    ports:
      - "27017:27017"
    networks:
      - net-web
    volumes:
      - ./mongodb/db:/data/db              # data dir
      - ./mongodb/log:/data/log            # log dir
    restart: always
    container_name: mongodb

  php:
    depends_on:
      - mysql
    build: ./php
    ports:
      - "9000:9000"
    networks:
      - net-web
    volumes:
      - ./php/conf/php.ini:/etc/php7/php.ini
      - ./php/conf/php-fpm.conf:/etc/php7/php-fpm.conf
      - ./php/conf/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./php/logs/error.log:/etc/php7/logs/error.log
      - ./www:/usr/local/nginx/html
    restart: always
    container_name: php

  nginx:
    depends_on:
      - php
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net-web
    volumes:
      - ./www:/usr/local/nginx/html
      - ./nginx/logs:/usr/local/nginx/logs
      - ./nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./nginx/conf/vhost:/usr/local/nginx/conf/vhost
      - ./nginx/cert:/usr/local/nginx/cert
    restart: always
    container_name: nginx

  nodejs:
    depends_on:
      - nginx
    build: ./nodejs
    ports:
      - "3000:3000"
    networks:
      - net-web
    volumes:
      - ./www:/app/src
    restart: always
    container_name: nodejs

networks:
  net-web:
