#
# Dockerfile for building PHP7 images
#
# https://github.com/wangyongdong/docker-alpine/tree/master/php
#

FROM wangyongdong/docker-alpine:latest
LABEL wangyongdong <wydchn@gmail.com>

ARG NODE_VER=10.8.0
ARG NPM_VER=6
ENV BUILD_APKS="curl git make gcc g++ python linux-headers paxctl binutils-gold ca-certificates"

# RUN apk -U add libgcc libstdc++ curl git make gcc g++ python linux-headers paxctl binutils-gold ca-certificates \
RUN apk -U add libgcc libstdc++ $BUILD_APKS \
 && cd /tmp \
 && curl --silent --ssl https://nodejs.org/dist/v$NODE_VER/node-v$NODE_VER.tar.gz | tar zxf - \
 && cd node-v$NODE_VER \
 && ./configure --prefix=/usr \
 && make -j1 && make install \
 && paxctl -cm /usr/bin/node \
 && npm install -g npm@$NPM_VER \
 && find /usr/lib/node_modules/npm -name test -o -name .bin -type d | xargs rm -rf \
 #&& apk del curl git make gcc g++ python linux-headers paxctl grep binutils-gold ca-certificates \
 && apk del $BUILD_APKS \
 && rm -rf /tmp/* \
    /var/cache/apk/* \
    /root/.npm \
    /root/.node-gyp \
    /usr/include \
    /usr/share/man \
    /usr/lib/node_modules/npm/man \
    /usr/lib/node_modules/npm/doc \
    /usr/lib/node_modules/npm/html

# Define working directory.

RUN mkdir -p /usr/local/nginx/html
WORKDIR /usr/local/nginx/html

EXPOSE 3000

CMD ["node"]